### ISSUE TITLE
libre: update to SDK 3.6.0

### ISSUE THREAD

**Issue by tormath1** [RocketChat/jitsi-maven-repository#3]
Hello, 

Any chance to get the SDK version to `3.6.0` for the `libre` [branch](https://github.com/RocketChat/jitsi-maven-repository/tree/libre) ?

I'm trying to port `Rocket.Chat.ReactNative` to `f-droid`, so I patched `android/build.gradle` while fixing other stuffs: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9943

It looks like we only need to run `./build.sh` with this line modified:
https://github.com/RocketChat/jitsi-maven-repository/blob/f7040ed779a967d725ee37fe2924effe25fc3f21/build.sh#L20-L21

I can have a look to submit a PR if it's ok with you. :)

**Comment by diegolmello** [comment]
That's great, @tormath1!
IIRC they said we should use Jitsi's libre instead of building it ourselves.
Maybe we should go that way?
Can you check if that's possible?

I've been reviewing some missing pieces for the release happening later this week, so I can't take a look on this _right now_, but I wanted to unblock you.

**Comment by tormath1** [comment]
@diegolmello 
> IIRC they said we should use Jitsi's libre instead of building it ourselves.

That's right, I just got a [comment](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9943#note_707999748) on my PR: 
> Since !9437 (merged) jitsi sdk need to be built from source.

Let's try this way then :) Feel free to close the issue / PR if you don't need it :ok_hand:

**Comment by tormath1** [comment]
@diegolmello so I gave a try by installing `jitsi-meet@android-sdk-3.6.0` from sources: https://gitlab.com/tormath1/fdroiddata/-/commit/4ca68227e06d6f457e0045c4f40906ede6fe3e10

but it tries now to install `3.7.0`:
```
Could not determine the dependencies of task ':app:lintVitalOfficialFossRelease'.
> Could not resolve all artifacts for configuration ':app:officialFossDebugRuntimeClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.7.0.
     Required by:
         project :app > project :react-native-jitsi-meet
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.7.0.
         > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.7.0/jitsi-meet-sdk-3.7.0.pom'.
            > Could not GET 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.7.0/jitsi-meet-sdk-3.7.0.pom'. Received status code 401 from server: Unauthorized
```

It seems the installation from sources is ignored. I'm really not used to work with `react` things, so I'm not sure where we can make the link between `react-native-jitsi-meet` and the lib we installed previously.

Do we need to do something with this line: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/package.json#L91 ?

EDIT: `react-native-jistsi-meet` adds a default value to `3.7.0` for `jitsi_version`, I initially remove this variable so it was using this default value. Let's try to get it back :)

**Comment by diegolmello** [comment]
Oh, it's actually a bug on the default version. It should be pointing to `3.6.0`, but it's not failing because we send the version from app https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/android/build.gradle#L21

https://github.com/RocketChat/react-native-jitsi-meet/blob/master/android/build.gradle#L52

Can you do it that way?

**Comment by diegolmello** [comment]
btw if you need a quick ping from me, you can DM me at https://open.rocket.chat/direct/diego.mello :)

**Comment by tormath1** [comment]
@diegolmello 
> it's not failing because we send the version from app https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/android/build.gradle#L21

Yeah I notified it - I initially removed this section so that's why it was requesting the default version. Now it seems to build correctly. :partying_face: 

> btw if you need a quick ping from me, you can DM me at https://open.rocket.chat/direct/diego.mello :)

Ok good to know. Do you have any clue to debug the app ? It currently does not install from the one generated by the `f-droid` CI :thinking: (see: https://gitlab.com/tormath1/fdroiddata/-/jobs/1697394627/artifacts/browse/tmp/) - I can maybe open an issue directly on https://github.com/RocketChat/Rocket.Chat.ReactNative to debug this.

**Comment by diegolmello** [comment]
@tormath1 maybe [here](https://gitlab.com/tormath1/fdroiddata/-/commit/5ae2b5d0a9550b3808c2d2f103c045b32308a119#58250d0c80626618993e2488e52245f1d98ee945_50_51) you should point to Jitsi's repo https://github.com/jitsi/jitsi-maven-repository/tree/master/releases 
I don't know how to target libre though.

To setup your env, follow [this](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md#how-to-run).
You can debug the app from Android Studio. Just make sure you select the proper build flavor.

**Comment by tormath1** [comment]
@diegolmello thanks - so I setup android tools (via command line), once the APK self-signed and pushed on the emulator, it crashes with:
```
10-21 18:05:58.287  8416  8445 E AndroidRuntime: FATAL EXCEPTION: mqt_js
10-21 18:05:58.287  8416  8445 E AndroidRuntime: Process: chat.rocket.android, PID: 8416
10-21 18:05:58.287  8416  8445 E AndroidRuntime: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
10-21 18:05:58.287  8416  8445 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-21 18:05:58.287  8416  8445 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
10-21 18:05:58.287  8416  8445 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-21 18:05:58.287  8416  8445 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
10-21 18:05:58.287  8416  8445 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-21 18:05:58.287  8416  8445 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
10-21 18:05:58.287  8416  8445 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

(Cross posting from: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9943#note_710643183)

**Comment by tormath1** [comment]
Won't be done - need to be built from jitsi-meet fork directly
